name: "Test"

on:
  push:

env:
  dotnet-version: 6.0.x
  python-version: 3.8
  project: Jellyfin.Plugin.MetaShark
  artifact: metashark

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release

    steps:
      - uses: actions/checkout@v3
      - name: Get tags (For CHANGELOG)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        id: dotnet
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Change default dotnet version
        run: |
          echo '{"sdk":{"version": "${{ steps.dotnet.outputs.dotnet-version }}"}}' > ./global.json
      - name: Initialize workflow variables
        id: vars
        run: |
          VERSION=$(echo "v1.7.3" | sed s/^v//)
          VERSION="$VERSION.0"
          echo ::set-output name=VERSION::${VERSION}
          echo ::set-output name=APP_NAME::$(echo '${{ env.artifact }}_${VERSION}')
      - name: Build
        run: |
          dotnet restore ${{ env.project }}/${{ env.project }}.csproj --no-cache
          dotnet publish --nologo --no-restore --configuration=Release --framework=net6.0 -p:Version=${{steps.vars.outputs.VERSION}} ${{ env.project }}
          mkdir -p artifacts
          zip -j ./artifacts/${{steps.vars.outputs.APP_NAME}}.zip ./${{ env.project }}/bin/Release/net6.0/${{ env.project }}.dll
          cp ./doc/logo.png ./artifacts/logo.png
      - name: Generate manifest
        run: cd artifacts && python3 ../scripts/generate_manifest.py ${{steps.vars.outputs.APP_NAME}}.zip v1.7.3
      - name: Deploy to jellyfin release repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT }}
          external_repository: cxfksword/jellyfin-release
          destination_dir: test
          publish_branch: master
          publish_dir: ./artifacts
